### ISSUE TITLE
fail2ban not updating

### ISSUE THREAD

**Issue by rtausend** [librenms/librenms-agent#121]
Hi there,

i don't get fail2ban application to get updated.

i tried:

./poller.php -h host -d -r -f -m applications

and get:

[RRD Disabled]fail2banSNMP[/usr/bin/snmpbulkwalk -v2c -c COMMUNITY -O qv -M /opt/librenms/mibs:/opt/librenms/mibs/supermicro -t 600 udp:HOSTNAME:161 .1.3.6.1.4.1.8072.1.3.2.3.1.2.8.102.97.105.108.50.98.97.110]
"88
88
asterisk 87
sshd 1"

SQL[UPDATE `applications` set `app_state` ='UNKNOWN',`timestamp` =NOW() WHERE `app_id` = '6']
RRD[update /opt/librenms/rrd/host/app-fail2ban-6.rrd N:U:U]

any idea whats going wrong here?

==========================================================
Component | Version
--------- | -------
LibreNMS  | 056ddbac0549b67160a5d4ee061ff31043c0f1f1
DB Schema | 186
PHP       | 5.6.30-0+deb8u1
MySQL     | 5.5.53-0+deb8u1
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2.1
==========================================================

Thanks!
Robert

**Comment by karlshea** [comment]
I also had fail2ban working and then recently it stopped. I got it working again by deleting the RRD files for it and letting the poller run on schedule a couple of times. Maybe something in the data changed to invalidate the existing RRDs? Not sure.

**Comment by laf** [comment]
A bug also existed which is now fixed. Update librenms instal
