### ISSUE TITLE
OpenWrt not detected

### ISSUE THREAD

**Issue by robimarko** [librenms/librenms-agent#126]
Hi,
LibreNMS keeps detecting all of my OpenWRT/Lede devices as Linux and then kernel version.
Version of OpenWRT or Lede makes no difference as well as kernel version.

I can manually over SSH use cat /etc/openwrt_version and I will get the version
It seems that discovery script may be broken?

**Comment by laf** [comment]
Are you using the distro script?

**Comment by robimarko** [comment]
Totally missed,script is for local instance.
I am using LibreNMS for SNMP monitoring.
