### ISSUE TITLE
Cannot run bind extension

### ISSUE THREAD

**Issue by thuynguyenduc** [librenms/librenms-agent#139]
I cannot run bind script as snmp extend as guided in http://docs.librenms.org/Extensions/Applications/#bind9-aka-named. When I try to use snmpwalk to test extend, i see an errror: "rndc: error: open: /etc/bind/rndc.key: permission denied" . I think we get this error because bind(named) service run as 'bind' user (Ubuntu) but snmp extend run as 'snmp' user. How to resolve it without add snmp user to bind group?

**Comment by laf** [comment]
@VVelox how do you handle this?

**Comment by VVelox** [comment]
Are you running SNMPD as a non-root user? If so you may need to setup like below.

    extend bind /usr/local/bin/sudo /etc/snmp/bind

And then add

    snmp ALL = NOPASSWD: /etc/snmp/bind

To /usr/local/etc/sudoers .

**Comment by tracernz** [comment]
Alternately you could use a different key for the snmp script (ideally with lower privileges), and alter the script to use rndc's `-k` option.
