### ISSUE TITLE
make smart plugin work behind raid controllers

### ISSUE THREAD

**Issue by evanrich** [librenms/librenms-agent#157]
Would be nice to have it accept parameters such as -d megaraid,0  to allow it to read smart data behind LSI based controllers. 

```
root@ubiquiti-docker:/var/cache# smartctl -d megaraid,0 -A /dev/sdc
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.9.0-4-amd64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000e   130   130   039    Old_age   Always       -       2125765038
  5 Reallocated_Sector_Ct   0x0033   100   100   001    Pre-fail  Always       -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       6191
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       66
 13 Read_Soft_Error_Rate    0x001e   130   100   000    Old_age   Always       -       19305634222
179 Used_Rsvd_Blk_Cnt_Tot   0x0033   100   100   010    Pre-fail  Always       -       0
180 Unused_Rsvd_Blk_Cnt_Tot 0x0032   100   100   000    Old_age   Always       -       3216
181 Program_Fail_Cnt_Total  0x003a   100   100   000    Old_age   Always       -       0
182 Erase_Fail_Count_Total  0x003a   100   100   000    Old_age   Always       -       0
184 End-to-End_Error        0x0032   100   100   000    Old_age   Always       -       0
194 Temperature_Celsius     0x0022   100   100   000    Old_age   Always       -       25
195 Hardware_ECC_Recovered  0x0032   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   100   100   000    Old_age   Always       -       0
201 Unknown_SSD_Attribute   0x0033   100   100   010    Pre-fail  Always       -       167906841130
202 Unknown_SSD_Attribute   0x0027   100   100   000    Pre-fail  Always       -       0
226 Unknown_SSD_Attribute   0x0032   100   100   000    Old_age   Always       -       102400
227 Unknown_SSD_Attribute   0x0032   100   100   000    Old_age   Always       -       0
228 Power-off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       3783637766
233 Media_Wearout_Indicator 0x0032   100   100   000    Old_age   Always       -       202552
245 Unknown_Attribute       0x0032   097   097   000    Old_age   Always       -       0
```

**Comment by laf** [comment]
Pull requests accepted. This repo is not actively maintained so you could be waiting a while for someone to add this support.

**Comment by evanrich** [comment]
@laf  thanks!  when I have some free time I'll get to hacking on it.. I'm having issues as is getting smart to work on non raided drives, doesn't seem to poll anything, despite /var/cache/smart being updated, librenms always says null.  once I get the base working, I'll try getting this to work.

**Comment by fake-name** [comment]
I'm looking at this too.

Right now, you can kind of be horrible and poke through the raid controller by abusing the way the smart script calls `smartctl`.

Basically, the script does `my $output=`$smartctl -A /dev/$disk`;`, with the last entry on the command line being the disk parameter from your `smart.config` file.

Since smartctl doesn't care too much about argument ordering, you can actually pass `-d megaraid,0` *after* your disk name. My `smart.config` looks like:

```
root@midxen:/etc/snmp# cat smart.config
smartctl=/usr/local/sbin/smartctl
cache=/var/cache/smart
sda -d megaraid,0
sda -d megaraid,1
sda -d megaraid,2
sda -d megaraid,3
sda -d megaraid,4
sda -d megaraid,5
sda -d megaraid,6
sda -d megaraid,7
sdb
sdc
sdd
sde
sdf
sdg
sdh
sdi
```

This actually gets you smart results for your disks, but the way the reporting works, all the RAID devices get smooshed together under the `sda` (or which ever disk you specify) disk name, so it doesn't *quite* work.

Possibly the person to ask would be @VVelox?

**Comment by VVelox** [comment]
Hoi! I'll take a look some time this week. :)

**Comment by fake-name** [comment]
Awesome, thanks!

I poked around a little bit, but I'm completely unfamilliar with perl.

**Comment by VVelox** [comment]
@laf Hey just pondering the best way to go about doing this. Would passing the disk name back as like sda_0 or sda,0 be better?

**Comment by VVelox** [comment]
@evanrich @fake-name 

https://github.com/librenms/librenms-agent/pull/226

May be of interest to a few people in this thread. This should actually take care of it.
