### ISSUE TITLE
OS-Updates slow

### ISSUE THREAD

**Issue by tim427** [librenms/librenms-agent#162]
All my Linux-based servers are SNMP-extended with "os-updates.sh". Sometimes, this scripts takes ages to complete (sometimes 10+ seconds), which results in a time-out on the poller script.

Result: Application OS-Updates will be remove and added later, when the scripts finishes in time, next time the poller requests this value.

As a suggestion/feature-request/discussion, I propose the following procedure:

1. Load the value of "os-updates.txt"
2. Immediately return this "old/previous" value
3. Check for updates in the background and save this to the "os-updates.txt"

Pro: Script return immediately, no time-outs nor high poller-times
Con: The returned value is "old", as in: the previous value.

What do you guys think? Is this acceptable? A improvement?

If so, I could rewrite the "os-update.sh"!

**Comment by crcro** [comment]
I also have this on every linux os monitored and never had an issue with timings. the only time where something like this happened was when opensuse repos had some issues and didn't return nothing for ages, or by simulating a faulty dns resolvers.

from this experience i would say that is more a connection/server related issue (and should be fixed at OS level) but i can see what you propose like a fallback solution in case of such situations.

**Comment by tim427** [comment]
Have to say: It works OK on most machines (still, its not returning in a split second)

Most problems I experience with CentOS-servers. Even-tough the "fastmirror" plugin is installed..

Servers are in the same network as others, same specs, etc. DNS is fast, uplink is perfect (1gbps stable)

I also agree with you, the best place to fix this "issue" is on OS-level, but apparently yum is kind of slow.

**Comment by tracernz** [comment]
Agreed, this should work like the smart script, and update a cache file periodically independently from SNMP.

**Comment by dracmic** [comment]
I know that a old threat but the suggested way pe tracernz works. I did it yesterday on a cpanel server.
