### ISSUE TITLE
Wrong comparison in zfs-freebsd

### ISSUE THREAD

**Issue by Serphentas** [librenms/librenms-agent#169]
On [line 118 of zfs-freebsd](https://github.com/librenms/librenms-agent/blob/master/snmp/zfs-freebsd#L118), the condition `$sysctls->{"kstat.zfs.misc.arcstats.size"} >= $sysctls->{"kstat.zfs.misc.arcstats.size"}` is checked.

It will in fact always return true, so perhaps one should double check what condition should be evaluated here.

I don't know ZFS stats in detail myself but it certainly doesn't look like it is the expected behaviour, given that an else statement follows right after.

**Comment by laf** [comment]
@VVelox?

**Comment by VVelox** [comment]
Hmm... looking.

**Comment by VVelox** [comment]
Thanks!

https://github.com/librenms/librenms-agent/pull/171 fixes this. Checked the zfs-stats scripted and updated it to the right one.

**Comment by Serphentas** [comment]
No problem. I'll also fix the Linux script in the same way.
