### ISSUE TITLE
LibreNMS detects wrong PHP version via validate.php?

### ISSUE THREAD

**Issue by thangnguyennang** [librenms/librenms-agent#176]
Hi,

LibreNMS worked fine on my old server. But, when it's being migrated to a new server, it dectects wrong PHP version via running the file validate.php, output:
Component | Version
LibreNMS  | 
DB Schema | ?
PHP       | 5.4.45
MySQL     | ?
RRDTool   | 1.3.8
SNMP      | NET-SNMP 5.5

[FAIL]  Composer has not been run, dependencies are missing [FIX] composer install --no-dev

My old server:
* OS: CentOS 7.x
* PHP: 7.0.23
* LibreNMS: 1.32

My new server:
* OS: CloudLinux Server release 6.9 
* PHP: 5.6.4 (with multi-PHP version support)
* LibreNMS: 1.39

Besides, when i run the command "composer install --no-dev" on my new server, it output with nothing (does not automatically install additional PHP packages).

**Comment by murrant** [comment]
You are on the wrong repo and help requests should be on https://community.librenms.org.

Can't report the wrong version, that is simply the output of php -v.  Check your config.
