### ISSUE TITLE
proxmox : keys on reference is experimental.....

### ISSUE THREAD

**Issue by MACscr** [librenms/librenms-agent#18]
```
root@stor1:/usr/lib/check_mk_agent/local# ./proxmox
keys on reference is experimental at /usr/share/perl5/PVE/API2Client.pm line 142.
<<<app-proxmox>>>
example
root@stor1:/usr/lib/check_mk_agent/local#
```

**Comment by f0o** [comment]
Tagging @tuxis-ie

**Comment by tuxis-ie** [comment]
That's a warning coming from /usr/share/perl5/PVE/API2Client.pm. Nothing we can do about that, except creating an issue with Proxmox.

**Comment by f0o** [comment]
@tuxis-ie is there any way to suppress it?

**Comment by tuxis-ie** [comment]
It's going to STDERR. Is it bothering anyone?

**Comment by f0o** [comment]
Stderr shouldnt influence the agent, all good then :)

**Comment by f0o** [comment]
@MACscr do you experience any polling/data issues because of this?
If not, I propose closing within 48h
