### ISSUE TITLE
smart script does not go well with enterprise devices

### ISSUE THREAD

**Issue by fionnb** [librenms/librenms-agent#180]
The smart script expects quite a number of vendor specific attributes to be printed by smartctl -A. 

However, in many circumstances, especially on disks run by some Enterprise host controllers like LSI Megaraid, often only general information is printed and not a single "numbered" vendor specific attribute is listed. The result is that the smart script returns an array of "null" and "0" values, totally unusable.

The script should detect the general absence of the character sequence "Vendor Specific SMART Attributes" (or alternatively "SMART Attributes Data Structure"), e.g.when it is called with "-g" and warn the user that monitoring wont work here.
Alternatively there could be a fallback mode in the script, that uses "smartctl -a" instead of "smartctl -A" to extract at least basic health info like errors corrected/uncorrected, temperature and such.

**Comment by VVelox** [comment]
I am curious, what does "smartctl --scan-open" report?

That said, currently working on rewriting a chunk of it to allow more complex results via allowing arbitrary switches to be specified for a device.

**Comment by VVelox** [comment]
https://github.com/librenms/librenms-agent/pull/226

There you go. Now does RAID and only uses --scan-open.

As to -a, I am curious got a example of where that returns anything useful but -A does not?

**Comment by VVelox** [comment]
#226 should resolve this and and not heard of any other issues in the last 3 weeks.
