### ISSUE TITLE
zfs-linux issue for CentOS7

### ISSUE THREAD

**Issue by voxnil** [librenms/librenms-agent#201]
[zfs-linux](https://github.com/librenms/librenms-agent/blob/master/snmp/zfs-linux) calls `/usr/bin/python3` and requires python3 >= python3.5 .
However, the typical repository for [python35](https://www.softwarecollections.org/en/scls/rhscl/rh-python35/) does not install python35 at `/usr/bin/python3`.

If possible change `!#/usr/bin/python3` to `#!/usr/bin/env python3` in `zfs-linux`.
Add documentation to advise recreation of override for `snmpd` on CentOS7 systems, e.g.:

`/etc/systemd/system/snmpd.service.d/rh-python35.conf`
```
[Service]
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/rh/rh-python35/root/usr/bin
Environment=LD_LIBRARY_PATH=/opt/rh/rh-python35/root/usr/lib64
```

**Comment by laf** [comment]
Why not just submit a pull request?

**Comment by voxnil** [comment]
I'm barely functional with git.

**Comment by voxnil** [comment]
#202
