### ISSUE TITLE
Portactivity returning only zero values

### ISSUE THREAD

**Issue by dracmic** [librenms/librenms-agent#221]
Hello, 

I found out that the compare string is wrong in portactivity extend script for snmp, it is comparing for example http with 80 which will not be equal ever.

Best regards.

**Comment by VVelox** [comment]
Running Linux I assume? Just looking at this and realized -n is not the equivalent of -S on FreeBSD. On another note, need to rewrite this abit to always use -n there is currently a bug that also crops up sometimes with Parse::Netstat with protocols that have a hyphen in their name.

**Comment by VVelox** [comment]
https://github.com/librenms/librenms-agent/pull/225

There. That should fix it. :)

**Comment by VVelox** [comment]
#225 resolved this and have not heard of any other issues. Closing.
