### ISSUE TITLE
Memcache Missing values !!

### ISSUE THREAD

**Issue by shahzaibcb** [librenms/librenms-agent#24]
We've recently installed librenms agent for memcached and graphs are already started to display but even the stats are there they don't look to be very useful. All important stats are missing such as , cache hits / cache miss / current connections. I can also see that executing memcached plugin from terminal provides these outputs but somehow graph of these values are missing : http://prntscr.com/b040tf .

**Comment by f0o** [comment]
According to the code, connection-count, misses and hits are being graphed.

Can you screenshot your graph please?

**Comment by shahzaibcb** [comment]
Maybe these are being graphed but the graphs title are different due to which i am unable to understand them. You can login into following URL using credentials as librenms / paklibrenms

http://5.254.102.90/device/device=3/tab=apps/app=memcached/instance=13/

**Comment by f0o** [comment]
Looking at the graphs it seems you're right. There are missing graphs for hit/misses.

The rrds should contain the DS already.

Tomorrow is holiday here so i got some free time to do the PR :)

**Comment by shahzaibcb** [comment]
great , so when will you be able to look into this issue ? :)

**Comment by f0o** [comment]
Tomorrow :)

**Comment by shahzaibcb** [comment]
Thanks, the product LibreNMS is great but what i've experienced that without any doubt it provides lot of detailed metrics but most of the time the important ones are missing. Like if i check the 'processes' tab it'll show all running processes without distinguishing between the top running processes which are actually consuming CPU / RAM etc. From my point of view (serverAdmin's view) , processes tab should show the top running processes at the top followed by processes which are not consuming anything most like the command 'top' which is very useful.

**Comment by f0o** [comment]
https://github.com/librenms/librenms/pull/3499
