### ISSUE TITLE
zfs-linux attempts to use a switch (-p) not yet ported from freebsd

### ISSUE THREAD

**Issue by simonjgreen** [librenms/librenms-agent#248]
https://github.com/librenms/librenms-agent/blob/ae3fdedcde24e2ce3d20677e6976f3787f35b7a0/snmp/zfs-linux#L98

The `-p` switch for parseable isn't available in most packages for ZFS on Linux. In fact, it was only committed to the upstream [late last year](https://github.com/GregorKopka/zfs/commit/b9df56877dab41cf29add6ce00152087b8c49350). Presumably this is a hangover from the original FreeBSD version of the command.

This is breaking on all Ubuntu up to and including 19.04.

**Comment by 12nick12** [comment]
I also have this issue. I would love to see a resolution. The only thing I can think is we can try and parse using zpool get and then parse that way, but my python/bash isn't good enough. If we do something like the folowing it gets us the data we need, it's just that is printed in rows not columns. 

zpool get -pH name,size,alloc,free,expandsz,frag,cap,dedup

**Comment by 12nick12** [comment]
Here's a quick workaround I did that prints what I think is the required data. I host it on my pastebin I can throw it on github if you'd like. https://link.nickshelp.info/vgAdV

**Comment by 12nick12** [comment]
Here's this on my github https://github.com/12nick12/librenms-zfs-linux-snmpd

**Comment by 12nick12** [comment]
I have move the repo to https://git.nicks.tv/nick/librenms-zfs-linux-snmpd

**Comment by simonjgreen** [comment]
@kkrumm1 was this closed due to a fix?

**Comment by nixtv** [comment]
I don't know why it was closed, it still doesn't work. My horrible implementation does.
