### ISSUE TITLE
deb/rpm/etc packaging?

### ISSUE THREAD

**Issue by BloodyIron** [librenms/librenms-agent#259]
Any chance we can get librenms-agent packaged in a way our package managers can be aware of it? A PPA/repo might be a good idea too, so we can easily get updates for it too.

The manual steps of installation now exist outside typical software management practices in many open source OS distros.

**Comment by VVelox** [comment]
Probably would be good to approach who ever is managing the LibreNMS package on those systems.

That said unfortunately this all is a bit of a mess with not everything really being cross platform etc. Sorta of a grab the bit you need and drop it in place.

**Comment by BloodyIron** [comment]
Typically those releasing the software (this github project) would build the packages and serve a PPA/repo. This is commonplace for many open source projects. Considering the software already works on multiple distros, packaging them for those distros in a way the package manager can be aware is plenty reasonable and achievable.

**Comment by BloodyIron** [comment]
why was this closed?
