### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by Setsuneh** [librenms/librenms-agent#26]
Hi,

I've got a problem with **memcached** plugin.
```
root@LibreNMS:/usr/lib/check_mk_agent/local# service nginx restart && /usr/lib/check_mk_agent/local/memcached
PHP Fatal error:  Uncaught Error: Class 'memcached' not found in /usr/lib/check_mk_agent/local/memcached:3
Stack trace:
#0 {main}
  thrown in /usr/lib/check_mk_agent/local/memcached on line 3
```

I use PHP 7.0 with repo dotdeb, an issue? Thanks

**Comment by f0o** [comment]
Do you have the memcached extension installed?

On 6 June 2016 14:03:14 CEST, Setsuneh <notifications@github.com> wrote:
>Hi,
>
>I've got a problem with **memcached** plugin.
>```
>root@LibreNMS:/usr/lib/check_mk_agent/local# service nginx restart &&
>/usr/lib/check_mk_agent/local/memcached
>PHP Fatal error:  Uncaught Error: Class 'memcached' not found in
>/usr/lib/check_mk_agent/local/memcached:3
>Stack trace:
>#0 {main}
>  thrown in /usr/lib/check_mk_agent/local/memcached on line 3
>```
>
>I use PHP 7.0 with repo dotdeb, an issue? Thanks
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/librenms/librenms-agent/issues/26

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Setsuneh** [comment]
Yep, **php7.0-memcached** only.
I've error drowing on graphs
```
<<<app-memcached>>>
a:1:{s:15:"localhost:11211";a:51:{s:3:"pid";i:11502;s:6:"uptime";i:701;s:4:"time";i:1465215020;s:7:"version";s:6:"1.4.21";s:8:"libevent";s:13:"2.0.21-stable";s:12:"pointer_size";i:64;s:11:"rusage_user";d:0.049992000000000002;s:13:"rusage_system";d:0.024996000000000001;s:16:"curr_connections";i:5;s:17:"total_connections";i:6;s:21:"connection_structures";i:6;s:12:"reserved_fds";i:20;s:7:"cmd_get";i:0;s:7:"cmd_set";i:0;s:9:"cmd_flush";i:0;s:9:"cmd_touch";i:0;s:8:"get_hits";i:0;s:10:"get_misses";i:0;s:13:"delete_misses";i:0;s:11:"delete_hits";i:0;s:11:"incr_misses";i:0;s:9:"incr_hits";i:0;s:11:"decr_misses";i:0;s:9:"decr_hits";i:0;s:10:"cas_misses";i:0;s:8:"cas_hits";i:0;s:10:"cas_badval";i:0;s:10:"touch_hits";i:0;s:12:"touch_misses";i:0;s:9:"auth_cmds";i:0;s:11:"auth_errors";i:0;s:10:"bytes_read";i:25;s:13:"bytes_written";i:1113;s:14:"limit_maxbytes";i:67108864;s:15:"accepting_conns";i:1;s:19:"listen_disabled_num";i:0;s:7:"threads";i:4;s:11:"conn_yields";i:0;s:16:"hash_power_level";i:16;s:10:"hash_bytes";i:524288;s:17:"hash_is_expanding";i:0;s:12:"malloc_fails";i:0;s:5:"bytes";i:0;s:10:"curr_items";i:0;s:11:"total_items";i:0;s:17:"expired_unfetched";i:0;s:17:"evicted_unfetched";i:0;s:9:"evictions";i:0;s:9:"reclaimed";i:0;s:17:"crawler_reclaimed";i:0;s:17:"lrutail_reflocked";i:0;}}
```

**Comment by murrant** [comment]
The output you attached indicates that the memcached agent plugin is working.  Did you install php7.0-memcached to get that to work?

Does `telnet HOSTNAME 6556` work?
