### ISSUE TITLE
Proxmox agent doesnt work

### ISSUE THREAD

**Issue by hackman61** [librenms/librenms-agent#28]
Hi,

When I start `/usr/lib/check_mk_agent/local/proxmox` , it say `keys on reference is experimental at /usr/share/perl5/PVE/API2Client.pm line 142.
<<<app-proxmox>>>
virt-01b
105/net0/4271661/1235810/teamviewer.econcept.local
500 Configuration file 'nodes/virt-01b/qemu-server/101.conf' does not exist`

does anybody know ho to solve this ?
Thank's !

Version : 

pve-manager/4.2-2/725d76f0 (running kernel: 4.4.6-1-pve)
librenms fresh installed from today on ubuntu 14.04

**Comment by f0o** [comment]
Tagging @tuxies-ie

**Comment by f0o** [comment]
Tagging @tuxis-ie

**Comment by tuxis-ie** [comment]
Hmm. Looks like a proxmox issue. Do you even have a vm with id 101? Does the mentioned file exist?

**Comment by einarjh** [comment]
As far as I can tell from some very cursory glances at the agent code and the API, it seems the proxmox agent tries to read lxc configurations from the qemu node in the API. (First it fetches nodes/$hostname/netstat, then it reads the VM IDs, and tries accessing them all via nodes/$hostname/qemu/$vmid/config). The problem with that approach is that Proxmox can host both VMs (qemu) and containers (lxc in Proxmox 4, openvz previously), and they're listed in different places in the API.

**Comment by tuxis-ie** [comment]
That's a very good point. I can look into that tomorrow, thanks!

**Comment by tuxis-ie** [comment]
@einarjh Can you try this patch?

**Comment by einarjh** [comment]
Tried it, it recognizes the lxe containers now, but curiously "name" isn't a value in that part of the API. You can query "hostname" for lxc: 
`my $vmname = $conn->get("/api2/json/nodes/$hostname/lxc/$vmid/config")->{'data'}->{'hostname'};`

While you're at it, qemu-machines that has the value "template" set to 1 should be ignored (they're templates and can't be run).
