### ISSUE TITLE
snmp/distro doesn't show PVE version on PVE host.

### ISSUE THREAD

**Issue by FingerlessGlov3s** [librenms/librenms-agent#282]
Hi,

When running the distro version detection script, if the host is PVE, it reports back as Debian 10, doesn't carry over the PVE version.

This can be easily fixed by adding ```IGNORE_OS_RELEASE=1``` after the if statement for /usr/bin/pveversion

Verified with latest version of PVE

Before: ```Debian GNU/Linux 10```
Afterr: ```Debian 10.3/PVE 6.1-8```

**Comment by FingerlessGlov3s** [comment]
After a nights sleep, I thought about pull requesting this change but thought there might be other Distro's with this issue so, not 100% which is the best way to go about it.

**Comment by SourceDoctor** [comment]
@FingerlessGlov3s is your issue still relevant?
Code has a match for Proxmox:
https://github.com/librenms/librenms-agent/blob/master/snmp/distro#L63

if it's still the case feel free to write a patch for it

**Comment by FingerlessGlov3s** [comment]
Hey @SourceDoctor 

Just tested it again, and it does match, it gets down to line 105, and changes to what ever os-release says
https://github.com/librenms/librenms-agent/blob/a8cb5b0112848010660cca4ebca26313fc625caf/snmp/distro#L105
a

To fix this I added "IGNORE_OS_RELEASE=1" to line 64 and it works a treat.

Shall I put a PR in for this or will you make a quick commit for it?

**Comment by SourceDoctor** [comment]
please write a PR

**Comment by FingerlessGlov3s** [comment]
PR has been made
https://github.com/FingerlessGlov3s/librenms-agent/pull/1

**Comment by FingerlessGlov3s** [comment]
PR Done

https://github.com/librenms/librenms-agent/pull/316
