### ISSUE TITLE
Linter changed OS detection for Raspbian

### ISSUE THREAD

**Issue by karlshea** [librenms/librenms-agent#360]
Old version detects `Raspbian 10.8`, new version detects `Debian 10.8`

Change in 25fb357809a38138677972783b3956f2f9c4cdb0 looks like it changed `sed 's/ //g'` from a tab to a space.

**Comment by Jellyfrog** [comment]
Hi could you check if https://github.com/librenms/librenms-agent/pull/363 fixes your problems?

**Comment by karlshea** [comment]
Yes, #363 fixes this.
