### ISSUE TITLE
how to include graphs from remote host

### ISSUE THREAD

**Issue by crcro** [librenms/librenms-agent#41]
I want to make something like:
- remote host with monitoring tools for hardware that don't expose their values via snmp or something usual (like emc storages, hp blade online admin modules etc).
- "import" that graphs to the "real host" in librenms, ie:
 * add the real emc storage processor in librenms (but nothing usefull is available) 
 * configure remote host with naviseccli (tool from emc to get data out) and export it via snmp (if possible, if not is there another way?)
 * "import" the remote host data/graphs to the real emc storage processor under librenms.

is this doable?

**Comment by laf** [comment]
I'd say this belongs as a discussion in the main librenms repo. It's basically getting towards what we want to do of allow non-snmp hosts to be added.

**Comment by crcro** [comment]
there is snmp in emc products but most important info (like luns/load etc) is given only by using a custom shell of their own

**Comment by crcro** [comment]
moved the discussion to community.librenms.org
