### ISSUE TITLE
os-updates.sh don't show "updates" on app page 

### ISSUE THREAD

**Issue by nerdalertdk** [librenms/librenms-agent#44]
Trying to get osupdate wokring, 
The script is working fin on multiple server, when running it terminal, i get the date in snmpwalk (see snip below) but it don't display a number on the app page

![image](https://cloud.githubusercontent.com/assets/3426495/17519097/c7159c96-5e4a-11e6-9232-74ef603de1eb.png)

```
root@librenms:/opt# snmpwalk -v 2c -c HIDEME IPADRESSS .1.3.6.1.4.1.8072.1.3.2
NET-SNMP-EXTEND-MIB::nsExtendNumEntries.0 = INTEGER: 1
NET-SNMP-EXTEND-MIB::nsExtendCommand."osupdate" = STRING: /opt/librenms-agent/snmp/os-updates.sh
NET-SNMP-EXTEND-MIB::nsExtendArgs."osupdate" = STRING:
NET-SNMP-EXTEND-MIB::nsExtendInput."osupdate" = STRING:
NET-SNMP-EXTEND-MIB::nsExtendCacheTime."osupdate" = INTEGER: 5
NET-SNMP-EXTEND-MIB::nsExtendExecType."osupdate" = INTEGER: exec(1)
NET-SNMP-EXTEND-MIB::nsExtendRunType."osupdate" = INTEGER: run-on-read(1)
NET-SNMP-EXTEND-MIB::nsExtendStorage."osupdate" = INTEGER: permanent(4)
NET-SNMP-EXTEND-MIB::nsExtendStatus."osupdate" = INTEGER: active(1)
NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."osupdate" = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutputFull."osupdate" = STRING: 0
NET-SNMP-EXTEND-MIB::nsExtendOutNumLines."osupdate" = INTEGER: 1
NET-SNMP-EXTEND-MIB::nsExtendResult."osupdate" = INTEGER: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."osupdate".1 = STRING: 0
```

got any clues ?

**Comment by murrant** [comment]
This was fixed recently.  This should have been posted to the main repository.  Thanks.

**Comment by nerdalertdk** [comment]
Just updated the os-updates.sh on 3 hosts, ran ./daily.php  waited 10-15min, still black App page.

both the old and the new os-updates.sh returned the correct amount of updates when runned locally on the servers.



INFO:
```
====================================
Version info:
Commit SHA: 633c4c4723e771297e44cb27b3a041550d2f00d7
DB Schema: 126
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.50-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2
```
```
root@librenms:/opt/librenms# snmpwalk -v 2c -c HIDEME IPADRESS .1.3.6.1.4.1.8072.1.3.2
NET-SNMP-EXTEND-MIB::nsExtendNumEntries.0 = INTEGER: 1
NET-SNMP-EXTEND-MIB::nsExtendCommand."osupdate" = STRING: /opt/librenms-agent/snmp/os-updates.sh
NET-SNMP-EXTEND-MIB::nsExtendArgs."osupdate" = STRING:
NET-SNMP-EXTEND-MIB::nsExtendInput."osupdate" = STRING:
NET-SNMP-EXTEND-MIB::nsExtendCacheTime."osupdate" = INTEGER: 5
NET-SNMP-EXTEND-MIB::nsExtendExecType."osupdate" = INTEGER: exec(1)
NET-SNMP-EXTEND-MIB::nsExtendRunType."osupdate" = INTEGER: run-on-read(1)
NET-SNMP-EXTEND-MIB::nsExtendStorage."osupdate" = INTEGER: permanent(4)
NET-SNMP-EXTEND-MIB::nsExtendStatus."osupdate" = INTEGER: active(1)
NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."osupdate" = STRING: 19
NET-SNMP-EXTEND-MIB::nsExtendOutputFull."osupdate" = STRING: 19
NET-SNMP-EXTEND-MIB::nsExtendOutNumLines."osupdate" = INTEGER: 1
NET-SNMP-EXTEND-MIB::nsExtendResult."osupdate" = INTEGER: 0
NET-SNMP-EXTEND-MIB::nsExtendOutLine."osupdate".1 = STRING: 19
```

this host have 19 updates

**Comment by laf** [comment]
You'll need to provide the output of:

`./poller.php -h HOSTNAME -d -r -f -m applications, unix-agent`

**Comment by nerdalertdk** [comment]
http://pastebin.com/FpNHPJtM

expire in 1 day

**Comment by laf** [comment]
This looks like it's logging correctly. Maybe it's a webui issue.

Please set the pastebin to non-expiring as I can't look at this now.

**Comment by nerdalertdk** [comment]
http://pastebin.com/9J8VaHpC

**Comment by nerdalertdk** [comment]
look at the problem, seams to be the create RDD line,

```
[RRD Disabled]RRD[create /opt/librenms/rrd/sc01.HOSTNAME/app-os-updates-5.rrd --step 300 DS:packages:GAUGE:600:0:U RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RRA:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440  RRA:MIN:0.5:1:720 RRA:MIN:0.5:6:1440     RRA:MIN:0.5:24:775     RRA:MIN:0.5:288:797  RRA:MAX:0.5:1:720 RRA:MAX:0.5:6:1440     RRA:MAX:0.5:24:775     RRA:MAX:0.5:288:797  RRA:LAST:0.5:1:1440 
```
All my RRD update have this after the command  --daemon unix:/var/run/rrdcached/rrdcached.sock]

**Comment by laf** [comment]
run `./validate.php`

**Comment by nerdalertdk** [comment]
Version info:
[WARN]    Your install is out of date: 9bcc31ca6eb308c04ffaee1186ec1fcd054bfa21 (Tue, 09 Aug 2016 21:19:06 +0000)
DB Schema: 126
PHP: 5.5.9-1ubuntu4.19
MySQL: 5.5.50-0ubuntu0.14.04.1
RRDTool: 1.4.7
SNMP: NET-SNMP version: 5.7.2

**Comment by laf** [comment]
Is that the complete output as we also output that the connection to MySQL was ok which is missing here.

**Comment by nerdalertdk** [comment]
sql is Working fin, the problems is that the rrd files is not generated and not updated as fare as I can tell

**Comment by crcro** [comment]
@nerdalertdk did you updated to the last version from git? the graph template had 2 fixes (from your pictures you got and old version of generic_v3_multiline.inc.php)

**Comment by crcro** [comment]
bump @nerdalertdk

**Comment by crcro** [comment]
bump @nerdalertdk ... or maybe close? :)

**Comment by nerdalertdk** [comment]
Hi 

Been busy with work, but it worked after ireinstalled librenms,
