### ISSUE TITLE
zfs-linux has issues on newer versions of ZFS

### ISSUE THREAD

**Issue by tuxis-ie** [librenms/librenms-agent#518]
https://github.com/librenms/librenms-agent/blob/master/snmp/zfs-linux errors on newer versions on ZFS because the format of /proc/spl/kstat/zfs/arcstats changed. There is no longer a 'p', but there are 'pm' and 'pd' values.

I now 'fixed' my local version with the following code:
```
    if "p" in STATS:
        P = STATS["p"]
    else:
        P = STATS["pd"]+STATS["pm"]
```

Not sure if that is completly correct, but maybe something to look at?

**Comment by VVelox** [comment]
@tuxis-ie Try `https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/zfs`.

Just looking at the current code and this should be handled.

**Comment by VVelox** [comment]
@tuxis-ie BTW what does /proc/spl/kstat/zfs/arcstats look like?
