### ISSUE TITLE
mysql script doesn't support unix sockets

### ISSUE THREAD

**Issue by Gorian** [librenms/librenms-agent#70]
The mysql script doesn't seem to support connecting to the mysql server over a unix socket. This is important for mysql servers like MariaDB that can authenticate users via unix_socket. This would allow us to run the mysql script on the localhost without embedding a password in the script. Please fix.

**Comment by tracernz** [comment]
The port is also hardcoded by the looks: https://github.com/librenms/librenms-agent/blob/master/snmp/mysql#L275
It doesn't look like PHP's mysqli extension is even capable of connecting to a unix socket.

**Comment by murrant** [comment]
Guys, did you try it?  The MySQL client library connects to a unix socket by default.

https://dev.mysql.com/doc/refman/5.5/en/connecting.html
