### ISSUE TITLE
Scripts from documentation missing in repo

### ISSUE THREAD

**Issue by markuspachali** [librenms/librenms-agent#8]
Hi all,
based on the documentation there should be some scripts for e.g. monitoring ntp-client and server but they are not in the agent-local folder and it's also not possible to enable them because there is no repository. So it looks like there is something missing or am I doing something wrong?

Best regards,
Markus

**Comment by f0o** [comment]
Those scripts arent part of the Agent I think.
As far as I know they are snmpd extension scripts.

**Comment by murrant** [comment]
ntp-client is built in to the check_mk agent.

I'm not aware of any ntp server monitoring.
