### ISSUE TITLE
Proxmox agent uses deprecated module

### ISSUE THREAD

**Issue by PhilRW** [librenms/librenms-agent#81]
PVE::API2Client was [removed in PVE 4.4-6](https://github.com/Blub/pve-manager/blob/master/debian/changelog.Debian). Also see [this commit](https://github.com/Blub/pve-manager/commit/11be8d6e47d08bf82ca8c5e2daa12ddb8f8ba976).

This breaks functionality with the Proxmox agent as it throws a `Can't locate PVE/API2Client.pm` error now.

**Comment by laf** [comment]
Are you submitting a pull request to fix this?

**Comment by PhilRW** [comment]
Yes, Thanks for the reminder. When I tried it last Github was not working properly.

**Comment by tsumaru720** [comment]
FWIW I've tested the changes to the proxmox script in my environment and it seems to work the same as before using the new API client.

As mentioned in the PR though, does require `libpve-apiclient-perl` from apt

**Comment by acgustafson** [comment]
Just started running this on a host and everything seems to be working so far after installing `libpve-apiclient-perl`. 

I am running pve-manager/4.4-12/e71b7a74 (running kernel: 4.4.40-1-pve)
