### ISSUE TITLE
 librenms-agent/snmp/exim-stats.sh resturns only frozen emails

### ISSUE THREAD

**Issue by alchemyx** [librenms/librenms-agent#82]
Hi,

I am trying to use  librenms-agent/snmp/exim-stats.sh with Exim app in LibreNMS. It returns only one line containing number of frozen emails. While in fact it should return also queue size:

./includes/polling/applications/exim-stats.inc.php:
```
[...]
$stats = snmp_get($device, $oid, '-Oqv');

echo ' '.$name;

list ($frozen, $queue) = explode("\n", $stats);
[...]
```

**Comment by crcro** [comment]
just checked this:

crc@smtp01:~$ sudo ./exim-stats.sh
[sudo] password for crc:
16
19
crc@smtp01:~$

if you run it without sudo then you won't get both values:

crc@smtp01:~$ ./exim-stats.sh
exim: permission denied
0
exim: permission denied

crc@smtp01:~$

**Comment by alchemyx** [comment]
Hi,

In my case it returns only one value - 0 as I have 0 frozen emails. It doesn't return queue size. And my queue has some mails 

Thanks

-- 
Michał Margula, michal@margula.pl
"W życiu piękne są tylko chwile" [Ryszard Riedel]

Dnia 11.02.2017 o godz. 01:25 crcro <notifications@github.com> napisał(a):

**Comment by alchemyx** [comment]
I would also add one thing - `wc -l` will always return one number, it is number of lines as per manual:

```
       -l, --lines
              print the newline counts
```

. So I have no idea how it is possible it returns you two numbers instead of one.

**Comment by alchemyx** [comment]
OK. Now is all clear. The link http://docs.librenms.org/Extensions/Applications/#exim-stats points to outdated version of exim-stats.sh. Sorry for not checking it thoroughly.
