### ISSUE TITLE
multiple apps broken since February 6th including bind and mysql

### ISSUE THREAD

**Issue by rbax82** [librenms/librenms-agent#96]
The bind and mysql application graphs appear to no longer function. A debug poller run shows it is no longer looking for these apps so I suspect it's an issue in the librenms repo. Example:
https://nms.baxterit.net/graphs/to=1488515700/id=7/type=application_mysql_connections/from=1485837300/ demo:demo
====reverb debug
Debug poller run of the unix agent: http://pastebin.com/iEVZYdLB
telnet to the agent port: http://pastebin.com/B3x9uf7z
====echo debug
http://paste.ubuntu.com/24100174/
telnet to other servers agent port: http://pastebin.com/m5kfubs4

**Comment by laf** [comment]
I'm running the latest master and mysql works fine, apache did up until a day ago but that's only because I switched to nginx.

You should update your install to start with.

**Comment by rbax82** [comment]
I have updated it, same result.
Reverb: http://paste.ubuntu.com/24125426/
Echo: http://paste.ubuntu.com/24125429/

**Comment by rbax82** [comment]
dmi apparently is also not updating in the GUI.

**Comment by xbeaudouin** [comment]
The Mysql snmp script doesn't seems to work with php7.0 :  
` php -version
PHP 7.0.16-3 (cli) (built: Feb 22 2017 10:03:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-3, Copyright (c) 1999-2017, by Zend Technologies
`

`./mysql
The MySQL extension is not loaded`

**Comment by rbax82** [comment]
bind was previously working under the unix agent...

**Comment by rbax82** [comment]
forget it
